"""Add upgrade and downgrade

Revision ID: 1c9d8fe6a4ea
Revises: 160ff9f906ed
Create Date: 2025-06-23 14:32:45.552622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9d8fe6a4ea'
down_revision: Union[str, None] = '160ff9f906ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_likes', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie_likes', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
